# Generated by Django 4.2.3 on 2023-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0003_alter_movie_detail_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
