# Generated by Django 4.2.3 on 2023-08-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0004_alter_movie_detail_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_detail',
            name='NEW_RELEASES',
            field=models.BooleanField(default=False),
        ),
    ]
