# Generated by Django 4.2.3 on 2023-08-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0005_movie_detail_new_releases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
