# Generated by Django 4.2.3 on 2023-10-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0007_watchlater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchlater',
        ),
    ]
