# Generated by Django 4.2.3 on 2023-10-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0009_watchlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
