# Generated by Django 4.2.3 on 2023-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0010_alter_movie_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
