# Generated by Django 4.2.3 on 2023-10-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0015_remove_userprofile_viewing_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='user.png', upload_to='profilepics/'),
        ),
    ]
