# Generated by Django 4.2.3 on 2023-10-20 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_buff', '0017_movie_detail_dislikes_movie_detail_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_detail',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='movie_detail',
            name='likes',
        ),
        migrations.AddField(
            model_name='movie_detail',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie_detail',
            name='likes',
            field=models.ManyToManyField(related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
