# Generated by Django 4.2.3 on 2023-10-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0018_remove_movie_detail_dislikes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_detail',
            name='dislikes',
        ),
    ]
