# Generated by Django 4.2.3 on 2023-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0019_remove_movie_detail_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
