# Generated by Django 4.2.3 on 2023-10-20 18:32

import django.contrib.sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0020_userprofile_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session_token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=django.contrib.sessions.models.Session),
        ),
    ]
