# Generated by Django 4.2.3 on 2023-10-20 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_buff', '0023_alter_movie_detail_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
