# Generated by Django 4.2.3 on 2023-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0025_alter_movie_detail_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_detail',
            name='actors',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='movie_detail',
            name='cbfc_certificate',
            field=models.CharField(blank=True, choices=[('U', 'U'), ('U/A', 'U/A'), ('A', 'A'), ('S', 'Ss')], max_length=5, null=True),
        ),
    ]
