# Generated by Django 4.2.3 on 2023-10-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0026_movie_detail_actors_movie_detail_cbfc_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='cbfc_certificate',
            field=models.CharField(blank=True, choices=[('U', 'U'), ('U/A', 'U/A'), ('A', 'A'), ('S', 'S')], max_length=5, null=True),
        ),
    ]
