# Generated by Django 4.2.3 on 2023-10-22 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_buff', '0027_alter_movie_detail_cbfc_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='actors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie_detail',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
