# Generated by Django 4.2.3 on 2023-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0028_alter_movie_detail_actors_alter_movie_detail_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_detail',
            name='movie_duration',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
