# Generated by Django 4.2.3 on 2023-10-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0029_movie_detail_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_detail',
            name='test_genre',
            field=models.CharField(blank=True, choices=[('science_fiction', 'Science Fiction'), ('action', 'Action')], max_length=15, null=True),
        ),
    ]
