# Generated by Django 4.2.3 on 2023-10-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0030_movie_detail_test_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='genre',
            field=models.CharField(choices=[('science_fiction', 'Science Fiction'), ('action', 'Action'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('animated', 'Animated')], max_length=15),
        ),
    ]
