# Generated by Django 4.2.3 on 2023-10-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0031_alter_movie_detail_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_detail',
            name='test_genre',
        ),
    ]
