# Generated by Django 4.2.3 on 2023-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0033_rename_cbfc_certificate_movie_detail_cbfc_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='browser_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='device_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='os_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
