# Generated by Django 4.2.3 on 2023-10-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_buff', '0034_userprofile_browser_name_userprofile_device_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='browser_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='device_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='os_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
